### ISSUE TITLE
Color settings are no longer applied correctly for physical theme with v0.1.9 release

### ISSUE THREAD

**Issue by alm7878** [wrodie/mixer-card#13]
## System Information

version | core-2025.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.3
os_name | Linux
os_version | 6.12.23-haos
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.5
Stage | running
Available Repositories | 2005
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 15.2
-- | --
update_channel | stable
supervisor_version | supervisor-2025.05.3
agent_version | 1.7.2
docker_version | 28.0.4
disk_total | 14.0 GB
disk_used | 7.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (8.0.0), Advanced SSH & Web Terminal (20.0.2), ESPHome Device Builder (2025.5.2), Samba share (12.5.1), Studio Code Server (5.19.3), Z-Wave JS UI (4.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 8
views | 19
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), enp1s0 (enabled, default, auto), hassio (disabled), docker0 (disabled), veth2c15969 (disabled), veth7fb0cc6 (disabled), veth76808c9 (disabled), vethb85b9ae (disabled), veth2263a6d (disabled), veth8a2ab91 (disabled), veth3e31919 (disabled), vethdb0b7f6 (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), enp1s0 (192.168.0.45/24), hassio (172.30.32.1/23), docker0 (172.30.232.1/23), veth2c15969 (), veth7fb0cc6 (), veth76808c9 (), vethb85b9ae (), veth2263a6d (), veth8a2ab91 (), veth3e31919 (), vethdb0b7f6 ()
ipv6_addresses | lo (::1/128), enp1s0 (fe80::c674:873b:d085:9fe/64), hassio (fe80::4c69:1cff:fe7d:87ab/64), docker0 (fe80::e02e:7ff:fee5:a05d/64), veth2c15969 (fe80::d093:e1ff:feeb:60ab/64), veth7fb0cc6 (fe80::2cc1:87ff:fec9:743c/64), veth76808c9 (fe80::60f9:26ff:feff:62a3/64), vethb85b9ae (fe80::6cbf:5cff:fe8c:a64a/64), veth2263a6d (fe80::50d5:91ff:fe81:23a/64), veth8a2ab91 (fe80::f083:c7ff:fe69:a826/64), veth3e31919 (fe80::6c01:dcff:fe52:2e66/64), vethdb0b7f6 (fe80::80c0:15ff:fe7d:fcf7/64)
announce_addresses | 192.168.0.45, fe80::c674:873b:d085:9fe

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 25, 2025 at 10:29 PM
-- | --
current_recorder_run | June 1, 2025 at 8:09 PM
estimated_db_size | 301.37 MiB
database_engine | sqlite
database_version | 3.48.0

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/wrodie/mixer-card/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After upgrading to v0.1.9 the color settings in the physical theme are no longer applied correctly.  The modern theme appears to be working correctly. I am using the default color settings.  As you can see in the attached image, the muted fader tracks should be red (correctly shown on the mute buttons) and the active channels should be green but are grayed out.

![Image](https://github.com/user-attachments/assets/06c0fc8c-8c1b-494e-ba39-b455fa81ab1d)

### Reproduction steps

1. Change to physical theme: faderTheme: physical
2. Change between mute and active and observe track colors.
3.
...

### Debug logs

```text
Available upon request.
```

### Diagnostics dump

Available upon request.

**Comment by alm7878** [comment]
I should have added the full config:
```
type: custom:custom-mixer-card
faderWidth: 75px
faderHeight: 400px
borderRadius: 12px
haCard: false
faderThumbColor: "#DDD"
faderTrackColor: "#DDD"
faderActiveColor: "#22ba00"
faderInactiveColor: "#F00"
faderTheme: physical
alwaysShowFaderValue: true
faders:
  - entity_id: input_number.multi_hdmi1_volume
    active_entity_id: switch.fader_hdmi1
    name: CH1
  - entity_id: input_number.multi_hdmi2_volume
    active_entity_id: switch.fader_hdmi2
    name: CH2
  - entity_id: input_number.multi_hdmi3_volume
    active_entity_id: switch.fader_hdmi3
    name: CH3
  - entity_id: input_number.multi_hdmi4_volume
    active_entity_id: switch.fader_hdmi4
    name: CH4
  - entity_id: input_number.onkyo_receiver_volume
    active_entity_id: switch.fader_master
    value_entity_id: sensor.onkyo_volume
    invert_active: true
    name: MASTER

```
